/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitsa;

import javax.swing.JOptionPane;
import usuario.GestorCuentas;
import usuario.Usuario;

/**
 *
 * @author Personal
 */
public class CrearCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearCuenta.class.getName());
    Usuario usuario;
    GestorCuentas gestor  = new GestorCuentas();
    IniciarSesion iniciarSesion  = new IniciarSesion();

    /** 
     * Creates new form registro
     */
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Registrar_Nombre = new javax.swing.JTextField();
        txt_RegistrarApellido1 = new javax.swing.JTextField();
        txt_RegistrarContraseña = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_registrar1 = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Registrar_Nombre.setBackground(new java.awt.Color(0, 20, 9));
        txt_Registrar_Nombre.setForeground(new java.awt.Color(255, 255, 0));
        txt_Registrar_Nombre.setBorder(null);
        txt_Registrar_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Registrar_NombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Registrar_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 200, 20));

        txt_RegistrarApellido1.setBackground(new java.awt.Color(0, 20, 9));
        txt_RegistrarApellido1.setForeground(new java.awt.Color(255, 255, 0));
        txt_RegistrarApellido1.setBorder(null);
        jPanel1.add(txt_RegistrarApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 136, 200, 20));

        txt_RegistrarContraseña.setBackground(new java.awt.Color(0, 20, 9));
        txt_RegistrarContraseña.setForeground(new java.awt.Color(255, 255, 0));
        txt_RegistrarContraseña.setBorder(null);
        jPanel1.add(txt_RegistrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 200, 20));

        jTextField1.setBackground(new java.awt.Color(0, 20, 9));
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2026-05-19 at 2.33.16 AM (2).jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        btn_registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 30));

        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar1ActionPerformed

        setVisible(false);
            iniciarSesion.setVisible(true);
    }//GEN-LAST:event_btn_registrar1ActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed

        if(txt_Registrar_Nombre.getText().isEmpty()  || txt_RegistrarContraseña.getText().isEmpty()   ||  txt_RegistrarApellido1.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "datos faltantes");
        }
        else{
            
            gestor.registrarEstudiante(txt_Registrar_Nombre.getText(),  txt_RegistrarContraseña.getText(), txt_RegistrarApellido1.getText());
            
            
            setVisible(false);
            iniciarSesion.setVisible(true);
            
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_Registrar_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Registrar_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Registrar_NombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_registrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_RegistrarApellido1;
    private javax.swing.JTextField txt_RegistrarContraseña;
    private javax.swing.JTextField txt_Registrar_Nombre;
    // End of variables declaration//GEN-END:variables
}
