/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vitsa;

import API.Controlador;
import API.GBIFService;
import API.MapaPanel;
import API.TablaPanel;
import javax.swing.JCheckBox;
import org.jxmapviewer.viewer.GeoPosition;
import usuario.Animales;
/**
 *
 * @author Usuario
 */
import usuario.Usuario;
public class mapa extends javax.swing.JInternalFrame {
    Usuario usu;
    
    /**
     * Creates new form mapa
     */
    
    MapaPanel mapa = new MapaPanel();
    public mapa() {
        initComponents();
        
        TablaPanel tablaPanel = new TablaPanel();
        double lat = 2.43823;
        double lon =  -76.61316;          
        String json = GBIFService.buscarEspecies(lat, lon);
        Controlador.procesarDatos(json, mapa, tablaPanel);
        mapa.getMap().setAddressLocation(new GeoPosition(lat, lon));
                mapa.getMap().setZoom(6);
                System.out.println(json);
            add(mapa);
        
            
    }
    public void recibirID(String id){
        mapa.usarID(id);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jCheckBox1.setText("Mostrar radios");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2026-05-24 at 12.32.56 PM (Pequeña) (Teléfono) (Personalizado).jpeg"))); // NOI18N
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        mapa.setMostrarDensidad(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
