/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitsa;

import API.Controlador;
import API.GBIFService;
import API.MapaPanel;
import API.TablaPanel;
import javax.swing.JFrame;
import org.jxmapviewer.viewer.GeoPosition;
import usuario.Usuario;
/**
 *
 * @author Personal
 */
public class Perfil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Perfil.class.getName());

     
    public Perfil() {       
        initComponents();
         
    }
    public void nombre(String nombre){
        lbl_Nombre_perfil.setText(nombre);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Nombre_perfil = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_mapa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Nombre_perfil.setForeground(new java.awt.Color(120, 156, 22));
        jPanel1.add(lbl_Nombre_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, 20));

        jTextField2.setBackground(new java.awt.Color(15, 32, 24));
        jTextField2.setForeground(new java.awt.Color(15, 32, 24));
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 290, 70));

        jTextField1.setBackground(new java.awt.Color(9, 22, 15));
        jTextField1.setForeground(new java.awt.Color(15, 32, 24));
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2026-05-13 at 9.28.11 AM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 490));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/0af8c4ddc058058065320ba5dad91003.gif"))); // NOI18N
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, -4, 330, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/39ff6a3e5733a9e870fbe4a3f82b8736.gif"))); // NOI18N
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 466, 530));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 720, 480));

        btn_mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mapaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mapaActionPerformed
        /*MapaPanel mapa new MapaPanel();
        TablaPanel tablaPanel = new TablaPanel();
        
        


        tablaPanel.getTabla().getSelectionModel().addListSelectionListener(e -> {

            int fila = tablaPanel.getTabla().getSelectedRow();

            if (fila != -1) {
                double lat = (double) tablaPanel.getTabla().getValueAt(fila, 5);
                double lon = (double) tablaPanel.getTabla().getValueAt(fila, 6);

              
            }
        });
        setVisible(true);
        double lat = 2.43823;
        double lon =  -76.61316;          
        String json = GBIFService.buscarEspecies(lat, lon);
        Controlador.procesarDatos(json, mapa, tablaPanel);
        mapa.getMap().setAddressLocation(new GeoPosition(lat, lon));
                mapa.getMap().setZoom(6);
                System.out.println(json);
                add(mapa);
                
                
        JFrame tablaFrame = new JFrame("Tabla de Animales");
        JFrame tablaFrame1 = new JFrame("Mapa de Animales");
        tablaFrame1.setSize(700, 500);
        tablaFrame1.setLocation(100, 200);
    tablaFrame.setSize(700, 500);
    tablaFrame.add(tablaPanel);
    tablaFrame1.add(mapa);
    tablaFrame.setLocation(650, 200);
    tablaFrame1.setVisible(true);
    tablaFrame.setVisible(true);*/
         mapa mapa  = new mapa();
         jDesktopPane1.add(mapa);
         mapa.setVisible(true);       
         Tabla tabla = new Tabla();
         jDesktopPane1.add(tabla);
         tabla.setVisible(true);
    }//GEN-LAST:event_btn_mapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Perfil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mapa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Nombre_perfil;
    // End of variables declaration//GEN-END:variables
}
