/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vitsa;

import API.Controlador;
import API.GBIFService;
import API.MapaPanel;
import API.TablaPanel;

/**
 *
 * @author Usuario
 */
public class Tabla extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
                TablaPanel tablaPanel = new TablaPanel();
                MapaPanel mapa = new MapaPanel();
        tablaPanel.getTabla().getSelectionModel().addListSelectionListener(e -> {
            
            int fila = tablaPanel.getTabla().getSelectedRow();

            if (fila != -1) {
                double lat = (double) tablaPanel.getTabla().getValueAt(fila, 5);
                double lon = (double) tablaPanel.getTabla().getValueAt(fila, 6);

              
            }
        });
        double lat = 2.43823;
        double lon =  -76.61316;          
        String json = GBIFService.buscarEspecies(lat, lon);
        Controlador.procesarDatos(json, mapa, tablaPanel);
        add(tablaPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
